name: Test GitHub Actions - Branch Label

on:
  pull_request_target:
    types: opened

jobs:
  SetLabels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Set Labels
        # uses: woocommerce/grow/branch-label@actions-v2
        uses: woocommerce/grow/packages/github-actions/actions/branch-label@update/108-nodejs-v20-github-actions-branch-label